// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3aqC_lLkOHtj7VHoYEclYYlxun1WDtgc',
    appId: '1:356214465176:web:2309bd5abb48252691e6ed',
    messagingSenderId: '356214465176',
    projectId: 'posbon-bfbe3',
    authDomain: 'posbon-bfbe3.firebaseapp.com',
    storageBucket: 'posbon-bfbe3.firebasestorage.app',
    measurementId: 'G-29E56G4H45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpnP3mJOLeAeLg7-jvXt_fC5IYkHoRIAE',
    appId: '1:356214465176:android:0e016036618cddda91e6ed',
    messagingSenderId: '356214465176',
    projectId: 'posbon-bfbe3',
    storageBucket: 'posbon-bfbe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9T7vNo00xy-YhoZDxE99Yk0qkvsJFQS0',
    appId: '1:356214465176:ios:b4714cbca8000c0791e6ed',
    messagingSenderId: '356214465176',
    projectId: 'posbon-bfbe3',
    storageBucket: 'posbon-bfbe3.firebasestorage.app',
    iosBundleId: 'com.example.posbon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9T7vNo00xy-YhoZDxE99Yk0qkvsJFQS0',
    appId: '1:356214465176:ios:b4714cbca8000c0791e6ed',
    messagingSenderId: '356214465176',
    projectId: 'posbon-bfbe3',
    storageBucket: 'posbon-bfbe3.firebasestorage.app',
    iosBundleId: 'com.example.posbon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3aqC_lLkOHtj7VHoYEclYYlxun1WDtgc',
    appId: '1:356214465176:web:a996d3739343cca591e6ed',
    messagingSenderId: '356214465176',
    projectId: 'posbon-bfbe3',
    authDomain: 'posbon-bfbe3.firebaseapp.com',
    storageBucket: 'posbon-bfbe3.firebasestorage.app',
    measurementId: 'G-BHBL583HWX',
  );
}
